### ISSUE TITLE
[Feature] remove deprecated columns

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_shopify_source#68] opened 2023-06-15 22:52 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

In [June 2023](https://fivetran.com/docs/applications/shopify/changelog#june2023), the connector was migrated to a new Shopify API version, in which the following relevant columns were deprecated
- `order_line.fulfillment_service`
- `order_line.destination_location_*` fields 
- `order_line.origin_location_*` fields 
- `order.total_price_usd`
- `order. processing_method`
- `customer.lifetime_duration`

we should mark them as deprecated in the src yml file and remove them from staging models 

### Describe alternatives you've considered

leave em 

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment] 2023-06-20 21:26
This is a duplicate of the [Issue #60](https://github.com/fivetran/dbt_shopify/issues/60) created in the transform package. This is currently being worked on in the active sprint. I will close this issue out as a duplicate.

**Closed by fivetran-joemarkiewicz** 2023-06-20 21:26 UTC
Labels: enhancement
